export const GETNEWSLIST='home1/page1/getNewsList'
export const SETNEWSLIST='home1/page1/setNewsList'
export const GETVIDEOSLIST='home1/page1/getVideosList'
export const SETVIDEOSLIST='home1/page1/setVideosList'
export const CHANGESEARCH='home1/page1/changeSearch'
export const CHANGEGOSEARCH='home1/page1/changeGoSearch'
export const CHANGETABPAGE='home1/page1/changeTabPage'