export const CHANGEUSERNAME='login/changeUsername'
export const CHANGEPASSWORD='login/changePassword'
export const LOGIN='login/login'
export const LOGINRESULT='login/loginResult'
export const RELOGIN='login/reLogin'
export const HANDLELOGOUT='login/handleLogOut'